#!/usr/bin/ruby -KU
# microcast streaminfo tool
# Copyright(c) 2011 by Christopher Abad
# mailto:aempirei@gmail.com
# aim:goim?screenname=ambient+empire
# http://www.twentygoto10.com
# git://github.com/aempirei/microcast.git

require 'rubygems'
require 'getoptlong'
require 'socket'

PROGRAM = 'streaminfo'
VERSION = '1.0'
ARG0 = File.basename(__FILE__)

DFLPORT = 80
DFLPATH = '/'
LOGGING = false

def parse_url(url)

	if url =~ /^(https?):\/\/([-\w.]+)(?::(\d+))?(.+)?/

		protocol = $1
		host = $2
		port = $3.nil? ? DFLPORT : $3
		path = $4.nil? ? DFLPATH : $4

		return [ protocol, host, port, path ]
	end

	return nil
end

def is_true?(arg)
	return ( [ 'true', '1', 'yes', 't', 'y' ].includes? arg.downcase )
end

module Enumerable
	def each_group(n,&block)
		left = self.dup
		while ( not left.empty? )
			block.call(left.take n)
			left = left.drop n
		end
	end
end

class BasicSocket
	def recv_bytes(n)
		data = ''

		while data.size < n
			delta = read(n - data.size)
			return nil if delta.nil?
			data += delta
		end

		return data
	end
end

class String

	def logdump(name, width=32)
		if LOGGING
			printf("< %d %s:\n", Time.now.to_i, name)
			puts hexdump(width)
			puts '>'
		end
	end

	def hexdump(width=32)
		
		lines = []
		
		split(//).map { |b| [ sprintf('%02x', b.ord), (b =~ /^[[:print:]]$/) ? b : '.' ] }.each_group(width) do |xs|
			hex = xs.map { |a,b| a }.join(' ')
			str = xs.map { |a,b| b }.join()
			lines << sprintf(' %-*s | %-*s |', width * 3, hex, width, str)
		end

		return lines.join("\n")
	end
end

def log(key,value)
	printf("= %d %s: %s\n", Time.now.to_i, key, value)
end

class ZConfig

	DFLMETA = true
	DFLMETAINT = 16384

	VERSION = [ 'MPEG 2.5', 'reserved', 'MPEG 2', 'MPEG 1' ]
	LAYER = [ 'reserved', 'Layer III', 'Layer II', 'Layer I' ]
	CRC16 = [ 'yes', 'no' ]
	BITRATE = [
		[ lambda { |v,l| [ 3 ].include?(v) and [ 3 ].include?(l) }, [ 'free', 32, 64, 96, 128, 160, 192, 224, 256, 288, 320, 352, 384, 416, 448, 'bad' ] ],
		[ lambda { |v,l| [ 3 ].include?(v) and [ 2 ].include?(l) }, [ 'free', 32, 48, 56,  64,  80,  96, 112, 128, 160, 192, 224, 256, 320, 384, 'bad' ] ],
		[ lambda { |v,l| [ 3 ].include?(v) and [ 1 ].include?(l) }, [ 'free', 32, 40, 48,  56,  64,  80,  96, 112, 128, 160, 192, 224, 256, 320, 'bad' ] ],
		[ lambda { |v,l| [0,2].include?(v) and [ 3 ].include?(l) }, [ 'free', 32, 48, 56,  64,  80,  96, 112, 128, 144, 160, 176, 192, 224, 256, 'bad' ] ],
		[ lambda { |v,l| [0,2].include?(v) and [1,2].include?(l) }, [ 'free',  8, 16, 24,  32,  40,  48,  56,  64,  80,  96, 112, 128, 144, 160, 'bad' ] ]
	]

	SAMPLERATE = [
		[ 11025, 12000,  8000, 'reserved' ], # MPEG 2.5
		[ 'bad', 'bad', 'bad', 'reserved' ], # reserved
		[ 22050, 24000, 16000, 'reserved' ], # MPEG 2
		[ 44100, 48000, 32000, 'reserved' ], # MPEG 1
	]

	PADDING = [ 'no', 'yes' ]
	PRIVACY = [ 'no', 'yes' ]
	MODE = [ 'stereo', 'joint stereo', 'dual mono', 'single mono' ]
	COPYRIGHT = [ 'no', 'yes' ]
	ORIGINAL = [ 'no', 'yes' ]
	EMPHASIS =  [ 'none', '50/15ms', 'reserved', 'CCIT J.17' ]
	FRAMESIZE = [ 'bad', 1152, 1152, 384 ]

	OPTION_BITS = [ [0,11],[11,2],[13,2],[15,1],[16,4],[20,2],[22,1],[23,1],[24,2],[26,2],[28,1],[29,1],[30,2] ]
	FRAME_HEADER_SZ = 4
	FRAME_CRC16_SZ = 2

	attr_accessor :protocol
	attr_accessor :host
	attr_accessor :port
	attr_accessor :path
	attr_accessor :url
	attr_accessor :socket
	attr_accessor :options
	attr_accessor :frames
	attr_accessor :datastream
	attr_accessor :meta
	attr_accessor :metaint

	def get_bitrate(v,l,br)

		BITRATE.each { |f,brs| return brs[br] if f.call(v,l) }

		return nil
	end

	def get_frame_size(l,br,sr,padding)

		return 'bad' unless br.is_a?(Numeric) and sr.is_a?(Numeric) and padding.is_a?(Numeric)

		if [1,2].include?(l)
			return ((144 * br * 1000 / sr) + padding).floor
		elsif [3].include?(l)
			return (((12 * br * 1000 / sr) + padding) * 4).floor
		else
			return 'bad'
		end
	end

	def initialize
		@options = []
		@frames = []
		@datastream = ''
		@meta = DFLMETA
		@metaint = DFLMETAINT
	end

	def startup

		raise 'no url specified' if @url.nil?

		@protocol, @host, @port, @path = parse_url @url

		raise 'url invalid' if @protocol.nil?
		
		# connect socket

		@socket.close unless @socket.nil?

		[ :protocol, :host, :port, :path ].each { |s| log(s, send(s)) }

		@socket = TCPSocket.open(@host, @port)

		# register at_exit

		Kernel.at_exit do
			@socket.close unless ( @socket.nil? or @socket.closed? )
		end

		# register SIGINT handler

		Kernel.trap('INT') do |signo|
			Kernel.trap(signo, 'SIG_IGN')
			puts "captured interrupt, exiting"
			exit
		end

		return true
	end

	def resp_ok?(line)

		raise 'no response received' if line.nil?

		line.chomp!

		line.logdump(:response)

		return true if line =~ /^(HTTP\/1\.[01]|ICY)\s+200\s+OK\s*$/

		return false
	end

	def get_options

		options = []

		while true
			line = @socket.readline
			raise 'getting options failed' if line.nil?
			line.chomp!
			break if line == ''
			options << line
		end

		return options.inject({}) do |a,option|
			a[$1] = $2 if option =~ /^([^:]+):\s*(.*)/
			a
		end
	end

	def request

		request_data = if @meta
			sprintf("GET %s HTTP/1.1\r\nHost: %s\r\nIcy-MetaData:1\r\n\r\n", @path, @host)
		else
			sprintf("GET %s HTTP/1.1\r\nHost: %s\r\n\r\n", @path, @host)
		end

		request_data.logdump(:request)

		@socket.write request_data

		if resp_ok?(@socket.readline)
			
			@options = get_options

			if @meta

				raise 'metaint missing from options' unless @options.has_key? 'icy-metaint'
				@metaint = @options['icy-metaint'].to_i
			end

			raise 'metaint is not a positive integer' if @metaint < 1

			return true
		end

		return false
	end

	def get_frame_header_fields(data32)

		frame_header = sprintf("%b", data32.unpack('N').first)

		return OPTION_BITS.map do |range|
			Integer ('0b' + frame_header[*range])
		end
	end

	def get_frame_header_offset(data)

		skip = 0

		until (data[skip + 0].ord == 0xff) and (data[skip + 1].ord >= 0xf0) and (data[skip + 1].ord <= 0xff)
			skip += 1
			return nil if skip + FRAME_HEADER_SZ == data.length
		end

		return skip
	end

	def frame_header_valid?(frame_header)
		return false if ( not frame_header.values.grep(/^(reserved|bad)$/).empty? )
		return false if frame_header['layer'] != 'Layer III'
		return true
	end

	def has_frame?(data)
		return ( not get_frame_header_offset(data).nil? )
	end

	def get_frames(data)

		frames = []

		while has_frame?(data)
			frame,data = get_frame(data)
			# puts '→ ' + data[0,32].hexdump
			break if frame.nil?
			frames << frame
		end

		return [ frames, data ]
	end

	def get_frame_header(frame_header_bytes)

		sync,version,layer,crc16off,br,sr,padding,privacy,mode,me,copyright,original,emphasis = get_frame_header_fields(frame_header_bytes)

		bitrate = get_bitrate(version,layer,br)

		return {
			'version'      => VERSION[version],
			'layer'        => LAYER[layer],
			'crc-16'       => CRC16[crc16off],
			'bit-rate'     => bitrate,															# bit rate in Kb/s
			'sample-rate'  => SAMPLERATE[version][sr],											# sample rate in hz
			'padding'      => PADDING[padding],
			'privacy'      => PRIVACY[privacy],
			'mode'         => MODE[mode],
			'copyright'    => COPYRIGHT[copyright],
			'original'     => ORIGINAL[original],
			'emphasis'     => EMPHASIS[emphasis],
			'frame-size'   => FRAMESIZE[layer],													# frame size in samples
			'frame-length' => get_frame_size(layer, bitrate, SAMPLERATE[version][sr], padding), # includes header and possible crc
		}
	end

	def get_frame(data)

		postponed = [ nil, data ]

		return postponed if data.size < FRAME_HEADER_SZ

		skipped_data = ''

		while true do

			skip = get_frame_header_offset(data)

			return postponed if skip.nil?

			skipped_data += data.slice!(0,skip)

			frame_header_bytes = data[0,FRAME_HEADER_SZ]

			frame_header = get_frame_header(frame_header_bytes)

			if frame_header_valid? frame_header
				# remove the frame header and now data just contains the tail data which is already saved in frame_header_bytes
				data.slice!(0,FRAME_HEADER_SZ)
				break
			else
				# add one byte of the invalid frame header to the pre data so that it gets skipped next iteration
				skipped_data += data.slice!(0)
			end
		end

		frame_header['skip-length'] = skipped_data.length

		if skipped_data.length > 0
			skipped_data.logdump(:skipped_data)
		end

		crc = nil

		if frame_header['crc-16'] == 'yes'
			# if the crc16 is not off then pull it from the tail data
			# put the data back and wait until later if theres not enough data
			return postponed if data.size < 2
			crc = data.slice!(0,FRAME_CRC16_SZ).unpack('n')
			frame_header['crc-16-value'] = crc
		end

		# make sure theres enough stream data to grab the frame data

		return postponed if data.length < frame_header['frame-length']

		# save the frame samples data minus the header and possible crc

		frame_header['data'] = data.slice!(0,frame_header['frame-length'] - FRAME_HEADER_SZ - (crc.nil? ? 0 : FRAME_CRC16_SZ))

		return [ frame_header, data ]
	end

	def read_meta
		sz = @socket.recv_bytes(1)
		raise 'meta header read failed' if sz.nil?
		sz = sz.ord * 16
		meta = @socket.recv_bytes(sz)
		raise 'could not read meta data' if meta.nil?
		return meta
	end

	def each_stream_block(&block)
		while next_stream_block()
			block.call()
		end
	end

	def next_stream_block

		# get a data chunk based on the meta-int value

		delta = @socket.recv_bytes(@metaint)
		raise 'could not read data stream' if delta.nil?
		@datastream += delta

		delta[0,128].logdump(:delta)

		if @meta
			meta = read_meta()

			@metalength = meta.length

			@metadata = meta.sub(/\0+$/, '').scan(/(\w+)=('[^']*'|"[^"]*");/).inject({}) do |acc,kv|
				kv[1] = $2 if kv[1] =~ /(['"])(.*)\1/
				acc[kv[0]] = kv[1]
				acc
			end
		end

		frames, @datastream = get_frames @datastream

		@frames += frames

		return true
	end
end

$config = ZConfig.new

OPTIONS = [
	[ [ '--url'    , '-u', GetoptLong::REQUIRED_ARGUMENT ], nil  , 'stream url'     ],
	[ [ '--meta'   , '-m', GetoptLong::REQUIRED_ARGUMENT ], :meta, 'get metadata'   ],
	[ [ '--help'   , '-h', GetoptLong::NO_ARGUMENT       ], nil  , 'help'           ],
	[ [ '--version', '-V', GetoptLong::NO_ARGUMENT       ], nil  , 'version'        ]
]

def usage

	width = 20

	print "\n"
	
	version()

	print "\nusage: " + ARG0 + " [options]\n\n"

	OPTIONS.each do |option,arg,desc|

		( long, short, params ) = option
		
		str = [ long, short ].compact.join(', ') + ' '
		str += arg.to_s.upcase unless arg.nil?

		printf("\t%-*s%s", width, str, desc)
		printf(' (default: %s)', $config.send(arg)) unless arg.nil?
		print "\n"
	end

	print "\n"

end

def version
	puts PROGRAM + ' ' + VERSION
end

opts = GetoptLong.new(*OPTIONS.map { |x| x.first })

opts.each do |opt,arg|
	case opt
		when '--url'
			$config.url = arg
		when '--meta'
			$config.meta = is_true?(arg)
		when '--help'
			usage()
			exit
		when '--version'
			version()
			exit
	end
end

unless $config.startup
	puts "initialization failed"
	exit false
end

unless $config.request
	puts "stream request failed"
	exit false
end

class Hash
	def log_all
		each { |k,v| log(k,v) }
	end
end

$config.options.log_all

$config.each_stream_block do

	$config.metadata.log_all if $config.meta

	log('frame-count', $config.frames.size)

	tally = 0
	pline = nil

	$config.frames.each do |f|

		line = sprintf("%s %s %3dKb/s %5dhz %s %s samples %d skipped %d data.size %d expected size %d (-4) = %d crc-16 %s padding %s",
			f['version'], f['layer'], f['bit-rate'], f['sample-rate'], f['mode'], f['emphasis'], f['frame-size'], f['skip-length'], f['data'].size, f['frame-length'], f['frame-length'] - 4, f['crc-16'], f['padding'])

		if line == pline
			tally += 1
		else
			printf("(%03d) %s\n", tally, pline) unless pline.nil?
			tally = 1
			pline = line
		end
	end

	$config.frames.last.log_all if LOGGING

	$config.frames.last['data'].logdump(:last_data)

	$config.datastream.logdump(:datastream)

	$config.frames.clear
end
